name: convert-encoding
author: gendloop
description: 'Convert file encoding'
inputs:
# Required
  input_coding:
    description: 'Input encoding'
    required: true
    default: 'UTF-8'
  output_coding:
    description: 'Output encoding'
    required: true
    default: 'UTF-8-BOM'
  path:
    description: "Path or file"
    required: true
    default: ""
# Optional
  token:
    description: 'Personal token'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: checkout-repo
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}

    - name: convert-encoding
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        script="${{ inputs.input_coding }}_to_${{ inputs.output_coding }}.sh"
        chmod +x ${{ github.action_path }}\scripts\$script ${{ inputs.path }}

    - name: git-push
      uses: gendloop/git-push@v1.0.0
      with:
        token: ${{ inputs.token }}
        commit: "chore: \\`${{ inputs.input_coding }}\\` => \\`${{ inputs.output_coding}}\\` : \\`${{ inputs.path }}\\`"
