name: Convert_Encoding

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      input_coding:
        description: 'Input encoding'
        required: false
        default: 'UTF-8'
      output_coding:
        description: 'Output encoding'
        required: false
        default: 'UTF-8-BOM'
      path:
        description: "Path or file"
        required: true
        default: "src/"

jobs:
  convert_encoding:
    runs-on: windows-latest
    steps:
      - name: convert-encoding
        uses: gendloop/convert-encoding@main
        with:
          input_coding: ${{ inputs.input_coding }}
          output_coding: ${{ inputs.output_coding }}
          path: ${{ inputs.path }}
